// Generated by sara-chen at 2026-04-08T15:22:52.213Z
/**
 * arc2-023 — invoice-notification-template Event Handler
 *
 * Typed event dispatcher for the the-sprint-squeeze subsystem. Subscribers
 * register against named event types and receive typed payloads.
 *
 * @author Sara Chen
 * @date 2026-04-08T15:22:52.213Z
 */

import { Logger } from '../../../packages/shared-utils/index.js';

const log = new Logger('arc2-023.events');

export interface EventMap {
  created: { id: string; at: Date };
  updated: { id: string; changed: string[] };
  deleted: { id: string };
  failed: { id: string; reason: string };
}

export type EventName = keyof EventMap;

export type Listener<K extends EventName> = (
  payload: EventMap[K],
) => void | Promise<void>;

export class Dispatcher {
  private readonly listeners = new Map<EventName, Set<Listener<EventName>>>();

  on<K extends EventName>(event: K, listener: Listener<K>): () => void {
    const set =
      this.listeners.get(event) ?? new Set<Listener<EventName>>();
    set.add(listener as Listener<EventName>);
    this.listeners.set(event, set);
    return () => set.delete(listener as Listener<EventName>);
  }

  async emit<K extends EventName>(
    event: K,
    payload: EventMap[K],
  ): Promise<void> {
    const set = this.listeners.get(event);
    if (!set || set.size === 0) {
      log.info(`invoice-notification-template ${event} had no listeners`);
      return;
    }
    log.info(`invoice-notification-template dispatch ${event} -> ${set.size} listener(s)`);
    for (const listener of set) {
      try {
        await (listener as Listener<K>)(payload);
      } catch (err) {
        log.warn(`invoice-notification-template listener failed: ${(err as Error).message}`);
      }
    }
  }

  off(event: EventName): void {
    this.listeners.delete(event);
  }
}

export const invoice-notification-templateDispatcher = new Dispatcher();
