// Generated by sara-chen at 2026-04-08T05:20:41.881Z
/**
 * arc1-001 — project-setup-&amp;-ci-configuration Validation Schemas
 *
 * Lightweight runtime validators for clean-baseline payloads. No external
 * schema library required so this can be reused in edge environments.
 *
 * @author Sara Chen
 * @date 2026-04-08T05:20:41.881Z
 */

import { Logger } from '../../../packages/shared-utils/index.js';

const log = new Logger('arc1-001.validate');

export interface ValidationIssue {
  path: string;
  message: string;
}

export interface ValidationResult<T> {
  ok: boolean;
  value?: T;
  issues: ValidationIssue[];
}

function fail<T>(issues: ValidationIssue[]): ValidationResult<T> {
  return { ok: false, issues };
}

function ok<T>(value: T): ValidationResult<T> {
  return { ok: true, value, issues: [] };
}

export interface CreateInput {
  name: string;
  ownerId: string;
  tags: string[];
}

export function validateCreate(input: unknown): ValidationResult<CreateInput> {
  const issues: ValidationIssue[] = [];
  if (!input || typeof input !== 'object') {
    return fail([{ path: '$', message: 'expected object' }]);
  }
  const obj = input as Record<string, unknown>;
  if (typeof obj.name !== 'string' || obj.name.length === 0) {
    issues.push({ path: 'name', message: 'required string' });
  }
  if (typeof obj.ownerId !== 'string') {
    issues.push({ path: 'ownerId', message: 'required string' });
  }
  if (!Array.isArray(obj.tags) || !obj.tags.every((t) => typeof t === 'string')) {
    issues.push({ path: 'tags', message: 'expected string[]' });
  }
  if (issues.length > 0) {
    log.warn(`project-setup-&amp;-ci-configuration create rejected: ${issues.length} issue(s)`);
    return fail(issues);
  }
  return ok(obj as unknown as CreateInput);
}

export interface UpdateInput {
  name?: string;
  tags?: string[];
}

export function validateUpdate(input: unknown): ValidationResult<UpdateInput> {
  if (!input || typeof input !== 'object') {
    return fail([{ path: '$', message: 'expected object' }]);
  }
  return ok(input as UpdateInput);
}

export const project-setup-&amp;-ci-configurationSchemas = {
  create: validateCreate,
  update: validateUpdate,
};
