// Generated by marcus-webb at 2026-04-08T05:34:15.734Z
{
  "version": "1.0",
  "description": "Tightened CIC thresholds for arc1-003 after incident",
  "appliedAt": "2026-04-08T05:34:15.734Z",
  "appliedBy": "Marcus Webb",
  "modules": {
    "arc1-003": {
      "cic_threshold": 0.92,
      "require_secondary_review": true,
      "block_ai_only_changes": true,
      "minimum_test_coverage": 85,
      "required_reviewers": ["sara.chen"],
      "flags": [
        "ghost_file_detection",
        "removed_function_audit",
        "secondary_endpoint_validation"
      ]
    }
  },
  "global": {
    "cic_threshold": 0.80,
    "require_secondary_review": false,
    "block_ai_only_changes": false,
    "minimum_test_coverage": 70
  }
}
