// Generated by sara-chen at 2026-04-08T05:29:53.102Z
/**
 * arc1-002 — auth-service-foundation Model + Store
 *
 * Domain entity with an in-memory CRUD store. Suitable as a starting point
 * before swapping in a real persistence layer.
 *
 * @author Sara Chen
 * @date 2026-04-08T05:29:53.102Z
 */

import { Logger } from '../../../packages/shared-utils/index.js';

const log = new Logger('arc1-002.store');

export interface Entity {
  readonly id: string;
  readonly version: number;
  name: string;
  status: 'draft' | 'active' | 'archived';
  ownerId: string;
  tags: string[];
  createdAt: Date;
  updatedAt: Date;
}

export type Draft = Omit<
  Entity,
  'id' | 'version' | 'createdAt' | 'updatedAt'
>;

export class Store {
  private readonly rows = new Map<string, Entity>();
  private seq = 0;

  create(draft: Draft): Entity {
    const now = new Date();
    const id = `auth-service-foundation_${++this.seq}`;
    const entity: Entity = {
      id,
      version: 1,
      createdAt: now,
      updatedAt: now,
      ...draft,
    };
    this.rows.set(id, entity);
    log.info(`created ${id}`);
    return entity;
  }

  get(id: string): Entity | undefined {
    return this.rows.get(id);
  }

  list(filter?: Partial<Pick<Entity, 'status' | 'ownerId'>>): Entity[] {
    const all = Array.from(this.rows.values());
    if (!filter) return all;
    return all.filter((row) =>
      Object.entries(filter).every(([k, v]) => (row as Record<string, unknown>)[k] === v),
    );
  }

  update(id: string, patch: Partial<Draft>): Entity {
    const existing = this.rows.get(id);
    if (!existing) throw new Error(` not found: ${id}`);
    const next: Entity = {
      ...existing,
      ...patch,
      version: existing.version + 1,
      updatedAt: new Date(),
    };
    this.rows.set(id, next);
    return next;
  }

  delete(id: string): boolean {
    return this.rows.delete(id);
  }
}

export const auth-service-foundationStore = new Store();
