// Generated by priya-k at 2026-04-08T05:44:00.978Z
/**
 * arc1-009 — Configuration & Types
 *
 * Shared configuration, constants, and type definitions
 * for the reporting-endpoints-in-api-client module.
 *
 * @author Priya K
 * @date 2026-04-08T05:44:00.978Z
 */

/** Environment-aware configuration for reporting-endpoints-in-api-client */
export interface Config {
  /** Whether the feature is enabled (default: true) */
  enabled: boolean;

  /** Base URL for external API calls */
  baseUrl: string;

  /** Request timeout in milliseconds (default: 10000) */
  timeoutMs: number;

  /** Maximum retry attempts for transient failures (default: 3) */
  maxRetries: number;

  /** Log level for this module */
  logLevel: 'debug' | 'info' | 'warn' | 'error';
}

/** Default configuration values */
export const DEFAULT_CONFIG: Config = {
  enabled: true,
  baseUrl: process.env._BASE_URL ?? 'http://localhost:3000',
  timeoutMs: 10_000,
  maxRetries: 3,
  logLevel: 'info',
};

/** Status codes used by the reporting-endpoints-in-api-client module */
export const STATUS = {
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  PENDING: 'pending',
  ERROR: 'error',
} as const;

export type Status = (typeof STATUS)[keyof typeof STATUS];

/** Feature flag keys for reporting-endpoints-in-api-client */
export const FEATURE_FLAGS = {
  ENABLE_V2: 'reporting-endpoints-in-api-client.enable_v2',
  ENABLE_METRICS: 'reporting-endpoints-in-api-client.enable_metrics',
  ENABLE_CACHING: 'reporting-endpoints-in-api-client.enable_caching',
} as const;

/**
 * Load configuration from environment variables with defaults.
 */
export function loadConfig(overrides: Partial<Config> = {}): Config {
  return {
    ...DEFAULT_CONFIG,
    ...overrides,
  };
}
