// Generated by marcus-webb at 2026-04-08T05:42:02.391Z
/**
 * arc1-006 — Analytics Module
 *
 * Typed metrics collection, aggregation functions, and date range queries
 * for the clean-baseline platform.
 *
 * @author Marcus Webb
 * @date 2026-04-08T05:42:02.391Z
 */

/** Metric event types tracked by the analytics system */
type MetricEventType =
  | 'page_view'
  | 'api_call'
  | 'user_signup'
  | 'checkout_started'
  | 'checkout_completed'
  | 'webhook_dispatched'
  | 'webhook_failed'
  | 'auth_success'
  | 'auth_failure';

/** A single recorded metric event */
interface MetricEvent {
  readonly id: string;
  readonly type: MetricEventType;
  readonly timestamp: Date;
  readonly metadata: Record<string, string | number | boolean>;
  readonly userId?: string;
}

/** Aggregation result for a time bucket */
interface AggregatedBucket {
  readonly bucketStart: Date;
  readonly bucketEnd: Date;
  readonly count: number;
  readonly uniqueUsers: number;
}

/** Date range filter */
interface DateRange {
  readonly from: Date;
  readonly to: Date;
}

/** Summary statistics for a metric type */
interface MetricSummary {
  readonly eventType: MetricEventType;
  readonly totalCount: number;
  readonly uniqueUsers: number;
  readonly firstSeen: Date | null;
  readonly lastSeen: Date | null;
  readonly avgPerDay: number;
}

/**
 * Validate that a date range is well-formed.
 * Throws if `from` is after `to` or range exceeds 90 days.
 */
function validateDateRange(range: DateRange): void {
  if (range.from > range.to) {
    throw new RangeError('DateRange.from must be before DateRange.to');
  }
  const ninetyDaysMs = 90 * 24 * 60 * 60 * 1000;
  if (range.to.getTime() - range.from.getTime() > ninetyDaysMs) {
    throw new RangeError('Date range must not exceed 90 days');
  }
}

export class AnalyticsCollector {
  private events: MetricEvent[] = [];

  /** Record a metric event with automatic timestamping */
  record(type: MetricEventType, metadata: MetricEvent['metadata'] = {}, userId?: string): MetricEvent {
    const event: MetricEvent = {
      id: `evt_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`,
      type,
      timestamp: new Date(),
      metadata,
      userId,
    };
    this.events.push(event);
    return event;
  }

  /** Query events by type within a date range */
  query(type: MetricEventType, range: DateRange): readonly MetricEvent[] {
    validateDateRange(range);
    return this.events.filter(
      (e) => e.type === type && e.timestamp >= range.from && e.timestamp <= range.to,
    );
  }

  /** Aggregate events into fixed-width time buckets */
  aggregate(
    type: MetricEventType,
    range: DateRange,
    bucketSizeMs: number,
  ): AggregatedBucket[] {
    validateDateRange(range);
    if (bucketSizeMs <= 0) {
      throw new RangeError('Bucket size must be positive');
    }

    const filtered = this.query(type, range);
    const buckets: Map<number, { count: number; users: Set<string> }> = new Map();

    for (const event of filtered) {
      const bucketKey =
        Math.floor((event.timestamp.getTime() - range.from.getTime()) / bucketSizeMs) *
          bucketSizeMs +
        range.from.getTime();

      let bucket = buckets.get(bucketKey);
      if (!bucket) {
        bucket = { count: 0, users: new Set() };
        buckets.set(bucketKey, bucket);
      }
      bucket.count++;
      if (event.userId) bucket.users.add(event.userId);
    }

    return Array.from(buckets.entries())
      .sort(([a], [b]) => a - b)
      .map(([key, bucket]) => ({
        bucketStart: new Date(key),
        bucketEnd: new Date(key + bucketSizeMs),
        count: bucket.count,
        uniqueUsers: bucket.users.size,
      }));
  }

  /** Generate a summary for a specific metric type across a date range */
  summarize(type: MetricEventType, range: DateRange): MetricSummary {
    const filtered = this.query(type, range);
    const userIds = new Set(filtered.map((e) => e.userId).filter(Boolean));
    const sorted = [...filtered].sort(
      (a, b) => a.timestamp.getTime() - b.timestamp.getTime(),
    );

    const daySpan = Math.max(
      1,
      (range.to.getTime() - range.from.getTime()) / (24 * 60 * 60 * 1000),
    );

    return {
      eventType: type,
      totalCount: filtered.length,
      uniqueUsers: userIds.size,
      firstSeen: sorted.length > 0 ? sorted[0].timestamp : null,
      lastSeen: sorted.length > 0 ? sorted[sorted.length - 1].timestamp : null,
      avgPerDay: Math.round((filtered.length / daySpan) * 100) / 100,
    };
  }

  /** Count total events by type (useful for dashboards) */
  countByType(): Record<MetricEventType, number> {
    const counts = {} as Record<MetricEventType, number>;
    for (const event of this.events) {
      counts[event.type] = (counts[event.type] ?? 0) + 1;
    }
    return counts;
  }

  /** Flush all events (for testing or batch export) */
  flush(): readonly MetricEvent[] {
    const flushed = [...this.events];
    this.events = [];
    return flushed;
  }
}
