// Generated by marcus-webb at 2026-04-08T15:34:33.472Z
/**
 * arc2-029 — sprint-review-scramble Report Generator
 * @author Marcus Webb
 * @date 2026-04-08T15:34:33.472Z
 */

interface ReportRow {
  date: string;
  metric: string;
  value: number;
}

// Copied from monthly-revenue-report.ts and adapted for sprint-review-scramble
export async function generatesprint-review-scrambleReport(
  startDate: string,
  endDate: string,
): Promise<string> {
  const rows = await fetchReportData(startDate, endDate);
  let csv = 'date,metric,value\n';

  // Same loop structure as monthly-revenue-report.ts
  for (const row of rows) {
    csv += `${row.date},${row.metric},${row.value}\n`;
  }

  return csv;
}

// Also copied from monthly-revenue-report.ts
export async function generatesprint-review-scrambleSummary(
  startDate: string,
  endDate: string,
): Promise<{ totalValue: number; rowCount: number; avgValue: number }> {
  const rows = await fetchReportData(startDate, endDate);

  let totalValue = 0;
  for (const row of rows) {
    totalValue += row.value;
  }

  // Duplicated calculation — could use the CSV generator above
  return {
    totalValue,
    rowCount: rows.length,
    avgValue: rows.length > 0 ? totalValue / rows.length : 0,
  };
}

// This function is basically identical to fetchMonthlyRevenueData()
// in monthly-revenue-report.ts but with a different table name
async function fetchReportData(startDate: string, endDate: string): Promise<ReportRow[]> {
  // Stub — in prod this queries the sprint-review-scramble table
  // Same query pattern as monthly-revenue-report.ts
  return [
    { date: startDate, metric: 'sprint-review-scramble_total', value: 1500 },
    { date: endDate, metric: 'sprint-review-scramble_total', value: 1800 },
  ];
}

// Also copied from monthly-revenue-report.ts — formats currency
function formatCurrency(amount: number): string {
  return `$${amount.toFixed(2)}`;
}

// Unused function — was in the original file, left here after copy
function formatPercentage(value: number): string {
  return `${(value * 100).toFixed(1)}%`;
}

export async function emailReport(
  startDate: string,
  endDate: string,
  recipients: string[],
): Promise<void> {
  const csv = await generatesprint-review-scrambleReport(startDate, endDate);
  const summary = await generatesprint-review-scrambleSummary(startDate, endDate);

  // Fetches data a THIRD time through summary — inefficient
  // TODO: refactor to single data fetch
  console.log(
    `Sending sprint-review-scramble report to ${recipients.join(', ')}:`,
    formatCurrency(summary.totalValue),
  );
}
