// Generated by priya-k at 2026-04-08T15:32:42.858Z
/**
 * arc2-027 — Webhook Endpoint Update Handler
 * @author Priya K
 * @date 2026-04-08T15:32:42.858Z
 */

import { Request, Response } from 'express';

interface WebhookEndpointUpdate {
  url?: string;
  events?: string[];
  active?: boolean;
}

/**
 * Update a webhook endpoint configuration.
 * No error path testing exists for this handler.
 */
export async function updateWebhookEndpoint(
  req: Request,
  res: Response,
): Promise<void> {
  const { endpointId } = req.params;
  const updates = req.body as WebhookEndpointUpdate;

  // Validate URL format if provided
  if (updates.url) {
    try {
      new URL(updates.url);
    } catch {
      res.status(400).json({ error: 'Invalid URL format' });
      return;
    }
  }

  // No test covers what happens when endpointId doesn't exist
  const existing = await findEndpoint(endpointId);
  if (!existing) {
    res.status(404).json({ error: 'Endpoint not found' });
    return;
  }

  // No test covers partial updates or invalid event types
  const updated = {
    ...existing,
    ...updates,
    updatedAt: new Date().toISOString(),
  };

  await saveEndpoint(updated);
  res.json(updated);
}

// Stubs
async function findEndpoint(id: string): Promise<Record<string, unknown> | null> {
  return null;
}

async function saveEndpoint(endpoint: Record<string, unknown>): Promise<void> {
  // persistence stub
}
