// Generated by sara-chen at 2026-04-08T05:40:17.297Z
/**
 * arc1-004 — Notification Template Update (Recovery)
 *
 * Clean notification template update with proper input validation
 * and test coverage. Shows improvement in code quality.
 *
 * @author Sara Chen
 * @date 2026-04-08T05:40:17.297Z
 */

import { z } from 'zod';

const NotificationDataSchema = z.object({
  recipientEmail: z.string().email(),
  recipientName: z.string().min(1).max(100),
  subject: z.string().min(1).max(200),
  templateId: z.enum(['welcome', 'alert', 'digest', 'reminder']),
  variables: z.record(z.string()).optional(),
});

type NotificationData = z.infer<typeof NotificationDataSchema>;

interface SendResult {
  messageId: string;
  status: 'queued' | 'sent' | 'failed';
  timestamp: string;
}

/** Escape HTML in template variables to prevent injection */
function escapeVariable(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

/**
 * Send a notification with validated data and proper escaping.
 */
export async function sendNotification(input: unknown): Promise<SendResult> {
  const data = NotificationDataSchema.parse(input);

  // Escape all template variables
  const safeVars: Record<string, string> = {};
  if (data.variables) {
    for (const [key, val] of Object.entries(data.variables)) {
      safeVars[key] = escapeVariable(val);
    }
  }

  const messageId = `msg_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;

  // In prod: enqueue to the notification service
  return {
    messageId,
    status: 'queued',
    timestamp: new Date().toISOString(),
  };
}

export { NotificationDataSchema, escapeVariable };
export type { NotificationData, SendResult };
