// Generated by sara-chen at 2026-04-08T05:44:41.750Z
/**
 * arc1-010 — Auth Middleware Tests
 *
 * Comprehensive test suite covering happy path, expired tokens,
 * malformed tokens, missing headers, and invalid signatures.
 *
 * @author Sara Chen
 * @date 2026-04-08T05:44:41.750Z
 */

import { describe, it, expect, beforeEach, vi } from 'vitest';
import { authMiddleware, requireRole } from './arc1-010';
import jwt from 'jsonwebtoken';

const TEST_SECRET = 'test-secret-key-do-not-use-in-prod';

function makeToken(overrides: Record<string, unknown> = {}, secret = TEST_SECRET): string {
  return jwt.sign(
    {
      sub: 'user-123',
      email: 'sara@acme.dev',
      roles: ['engineer'],
      ...overrides,
    },
    secret,
    { expiresIn: '1h' },
  );
}

function mockReqRes(authHeader?: string) {
  const req = { headers: { authorization: authHeader } } as any;
  const res = {
    status: vi.fn().mockReturnThis(),
    json: vi.fn().mockReturnThis(),
    setHeader: vi.fn(),
  } as any;
  const next = vi.fn();
  return { req, res, next };
}

describe('authMiddleware', () => {
  const middleware = authMiddleware(TEST_SECRET);

  it('passes valid token and attaches auth context', () => {
    const token = makeToken();
    const { req, res, next } = mockReqRes(`Bearer ${token}`);

    middleware(req, res, next);

    expect(next).toHaveBeenCalledOnce();
    expect(req.auth).toBeDefined();
    expect(req.auth.userId).toBe('user-123');
    expect(req.auth.email).toBe('sara@acme.dev');
    expect(req.auth.roles).toEqual(['engineer']);
  });

  it('rejects missing Authorization header', () => {
    const { req, res, next } = mockReqRes(undefined);

    middleware(req, res, next);

    expect(next).not.toHaveBeenCalled();
    expect(res.status).toHaveBeenCalledWith(401);
    expect(res.json).toHaveBeenCalledWith({ error: 'AUTH_MISSING_HEADER' });
  });

  it('rejects malformed Authorization header', () => {
    const { req, res, next } = mockReqRes('Token abc123');

    middleware(req, res, next);

    expect(next).not.toHaveBeenCalled();
    expect(res.status).toHaveBeenCalledWith(401);
    expect(res.json).toHaveBeenCalledWith({ error: 'AUTH_MALFORMED_TOKEN' });
  });

  it('rejects expired token', () => {
    const token = jwt.sign(
      { sub: 'user-123', email: 'sara@acme.dev', roles: ['engineer'] },
      TEST_SECRET,
      { expiresIn: '-1s' },
    );
    const { req, res, next } = mockReqRes(`Bearer ${token}`);

    middleware(req, res, next);

    expect(next).not.toHaveBeenCalled();
    expect(res.status).toHaveBeenCalledWith(401);
    expect(res.json).toHaveBeenCalledWith({ error: 'AUTH_EXPIRED_TOKEN' });
  });

  it('rejects token signed with wrong secret', () => {
    const token = makeToken({}, 'wrong-secret');
    const { req, res, next } = mockReqRes(`Bearer ${token}`);

    middleware(req, res, next);

    expect(next).not.toHaveBeenCalled();
    expect(res.status).toHaveBeenCalledWith(401);
    expect(res.json).toHaveBeenCalledWith({ error: 'AUTH_INVALID_SIGNATURE' });
  });

  it('sets X-Token-Refresh header when token is near expiry', () => {
    const token = jwt.sign(
      { sub: 'user-123', email: 'sara@acme.dev', roles: ['engineer'] },
      TEST_SECRET,
      { expiresIn: '2m' }, // within 5-minute refresh threshold
    );
    const { req, res, next } = mockReqRes(`Bearer ${token}`);

    middleware(req, res, next);

    expect(next).toHaveBeenCalled();
    expect(res.setHeader).toHaveBeenCalledWith('X-Token-Refresh', 'true');
  });
});

describe('requireRole', () => {
  it('allows request with matching role', () => {
    const { req, res, next } = mockReqRes();
    req.auth = { userId: 'user-123', email: 'sara@acme.dev', roles: ['admin'], tokenExpiresAt: new Date() };

    requireRole('admin')(req, res, next);

    expect(next).toHaveBeenCalledOnce();
  });

  it('rejects request with insufficient role', () => {
    const { req, res, next } = mockReqRes();
    req.auth = { userId: 'user-123', email: 'sara@acme.dev', roles: ['engineer'], tokenExpiresAt: new Date() };

    requireRole('admin')(req, res, next);

    expect(next).not.toHaveBeenCalled();
    expect(res.status).toHaveBeenCalledWith(403);
  });
});
