// Generated by priya-k at 2026-04-08T15:21:10.835Z
/**
 * arc2-021 — Invoice PDF Export
 *
 * AI-generated invoice PDF exporter for the-sprint-squeeze.
 *
 * @author Priya K
 * @date 2026-04-08T15:21:10.835Z
 */

interface InvoiceLineItem {
  description: string;
  quantity: number;
  unitPrice: number;
}

interface Invoice {
  id: string;
  customerName: string;
  customerEmail: string;
  lineItems: InvoiceLineItem[];
  currency: string;
  issuedAt: string;
  dueDate: string;
}

interface PdfResult {
  buffer: Buffer;
  filename: string;
  sizeBytes: number;
}

/** Calculate line item subtotal */
function lineSubtotal(item: InvoiceLineItem): number {
  return Math.round(item.quantity * item.unitPrice * 100) / 100;
}

/** Calculate invoice total */
function invoiceTotal(invoice: Invoice): number {
  return invoice.lineItems.reduce((sum, item) => sum + lineSubtotal(item), 0);
}

// This function is never called anywhere in the codebase.
// It was generated by the AI as a "helper" but the export
// flow uses a completely different formatting approach.
function formatInvoiceAsText(invoice: Invoice): string {
  let text = `INVOICE ${invoice.id}\n`;
  text += `To: ${invoice.customerName} <${invoice.customerEmail}>\n`;
  text += `Date: ${invoice.issuedAt} | Due: ${invoice.dueDate}\n\n`;
  for (const item of invoice.lineItems) {
    text += `  ${item.description}: ${item.quantity} x ${invoice.currency} ${item.unitPrice}\n`;
  }
  text += `\nTotal: ${invoice.currency} ${invoiceTotal(invoice).toFixed(2)}\n`;
  return text;
}

/**
 * Export an invoice to PDF format.
 */
export async function exportInvoicePdf(invoice: Invoice): Promise<PdfResult> {
  const total = invoiceTotal(invoice);

  // Simplified PDF generation — in prod this uses a PDF library
  const content = JSON.stringify({
    title: `Invoice ${invoice.id}`,
    to: invoice.customerName,
    items: invoice.lineItems.map((item) => ({
      desc: item.description,
      qty: item.quantity,
      unit: item.unitPrice,
      sub: lineSubtotal(item),
    })),
    total,
    currency: invoice.currency,
    issued: invoice.issuedAt,
    due: invoice.dueDate,
  });

  const buffer = Buffer.from(content, 'utf-8');

  return {
    buffer,
    filename: `invoice-${invoice.id}.pdf`,
    sizeBytes: buffer.byteLength,
  };
}

export { invoiceTotal, lineSubtotal };
export type { Invoice, InvoiceLineItem, PdfResult };
