// Generated by priya-k at 2026-04-13T17:07:53.964Z
/**
 * arc2-021 — Ghost File Removal & Validation Restoration
 *
 * This diff:
 *   1. Deletes the ghost token-refresh module (was never imported)
 *   2. Restores the validateSecondaryEndpoint function
 *
 * @author Priya K
 * @date 2026-04-13T17:07:53.964Z
 */

// --- FILE DELETED: src/auth/token-refresh.ts ---
// Reason: ghost file — not imported anywhere in the codebase.
// The module was generated during the AI-assisted refactor but
// never wired into the auth flow. No runtime code references it.
// If token refresh is needed, it should be designed and reviewed
// as a standalone feature with proper integration tests.

// --- RESTORED in src/auth/jwt-verify.ts ---

import jwt from 'jsonwebtoken';

interface AuthResult {
  ok: boolean;
  auth?: { userId: string; email: string; roles: string[] };
  code?: number;
  message?: string;
}

interface EndpointConfig {
  secret: string;
  allowedRoles: string[];
}

/**
 * Validate a token against the secondary endpoint registry.
 *
 * This function was removed during the AI-assisted refactor,
 * which caused partner API callbacks to bypass endpoint-specific
 * role restrictions. Restored per incident review.
 */
export function validateSecondaryEndpoint(
  token: string,
  endpointId: string,
  endpointRegistry: Map<string, EndpointConfig>,
): AuthResult {
  const endpoint = endpointRegistry.get(endpointId);
  if (!endpoint) {
    return { ok: false, code: 404, message: `Unknown endpoint: ${endpointId}` };
  }

  try {
    const decoded = jwt.verify(token, endpoint.secret) as {
      sub: string;
      email: string;
      roles: string[];
    };

    const hasRole = endpoint.allowedRoles.some((r) => decoded.roles.includes(r));
    if (!hasRole) {
      return { ok: false, code: 403, message: 'Insufficient endpoint permissions' };
    }

    return {
      ok: true,
      auth: { userId: decoded.sub, email: decoded.email, roles: decoded.roles },
    };
  } catch {
    return { ok: false, code: 401, message: 'Invalid endpoint token' };
  }
}
