// Generated by marcus-webb at 2026-04-08T15:31:52.447Z
/**
 * arc2-026 — Checkout Flow
 * @author Marcus Webb
 * @date 2026-04-08T15:31:52.447Z
 */

import { Request, Response } from 'express';

interface CheckoutRequest {
  userId: string;
  items: { productId: string; quantity: number; price: number }[];
  paymentMethod: string;
  couponCode?: string;
}

// TODO: add proper input validation
export async function handleCheckout(req: Request, res: Response): Promise<void> {
  const body = req.body as CheckoutRequest;

  // Calculate total — not checking for negative prices or zero quantities
  let total = 0;
  for (const item of body.items) {
    total += item.price * item.quantity;
  }

  // Apply coupon — just trusting the value from the client
  if (body.couponCode) {
    const discount = await lookupCoupon(body.couponCode);
    total = total - discount;
  }

  // Charge — no idempotency key, no retry logic
  const charge = await processPayment(body.userId, body.paymentMethod, total);

  if (charge.success) {
    // Create order — not wrapping in a transaction
    const order = await createOrder(body.userId, body.items, charge.chargeId);
    res.json({ orderId: order.id, total });
  } else {
    res.status(400).json({ error: 'Payment failed' });
  }
}

async function lookupCoupon(code: string): Promise<number> {
  // Stub — in prod this hits the coupons service
  // Not checking expiry or usage limits
  return code === 'SAVE10' ? 10 : 0;
}

async function processPayment(
  userId: string,
  method: string,
  amount: number,
): Promise<{ success: boolean; chargeId: string }> {
  // Stub — real impl calls Stripe
  return { success: true, chargeId: `ch_${Date.now()}` };
}

async function createOrder(
  userId: string,
  items: CheckoutRequest['items'],
  chargeId: string,
): Promise<{ id: string }> {
  // Stub — real impl writes to the orders table
  return { id: `ord_${Date.now()}` };
}

// Export for the router
export default handleCheckout;
