// Generated by marcus-webb at 2026-04-08T05:43:23.824Z
/**
 * arc1-008 — Barrel Export
 *
 * Re-exports public API for the rate-limiting-utility-in-shared-utils module.
 *
 * @author Marcus Webb
 * @date 2026-04-08T05:43:23.824Z
 */

// --- Types ---
export type { Config } from './config.js';
export type { Record, CreateInput } from './types.js';

// --- Core ---
export { default as Router } from './routes.js';
export { Service } from './service.js';

// --- Utilities ---
export { validate } from './validation.js';
