// Generated by sara-chen at 2026-04-08T05:44:41.750Z
/**
 * arc1-010 — comprehensive-test-coverage-boost Utility Helpers
 *
 * Pure helper functions for the clean-baseline domain. Side-effect free
 * so they are easy to unit test and tree-shake.
 *
 * @author Sara Chen
 * @date 2026-04-08T05:44:41.750Z
 */

import { Logger } from '../../../packages/shared-utils/index.js';

const log = new Logger('arc1-010.util');

export function slugify(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

export function chunk<T>(items: readonly T[], size: number): T[][] {
  if (size <= 0) throw new Error('chunk size must be > 0');
  const out: T[][] = [];
  for (let i = 0; i < items.length; i += size) {
    out.push(items.slice(i, i + size));
  }
  return out;
}

export function uniqueBy<T, K>(items: readonly T[], key: (t: T) => K): T[] {
  const seen = new Set<K>();
  const out: T[] = [];
  for (const it of items) {
    const k = key(it);
    if (!seen.has(k)) {
      seen.add(k);
      out.push(it);
    }
  }
  return out;
}

export function clamp(n: number, min: number, max: number): number {
  return Math.min(Math.max(n, min), max);
}

export function safeParseJSON<T>(raw: string, fallback: T): T {
  try {
    return JSON.parse(raw) as T;
  } catch (err) {
    log.warn(`comprehensive-test-coverage-boost parse failed: ${(err as Error).message}`);
    return fallback;
  }
}

export function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  if (ms < 60_000) return `${(ms / 1000).toFixed(1)}s`;
  return `${(ms / 60_000).toFixed(1)}m`;
}

export const comprehensive-test-coverage-boostHelpers = {
  slugify,
  chunk,
  uniqueBy,
  clamp,
  safeParseJSON,
  formatDuration,
};
