// Generated by marcus-webb at 2026-04-08T05:34:15.734Z
/**
 * arc1-003 — Webhook Dispatcher
 *
 * Dispatches webhook events to registered endpoints with retry logic,
 * signature verification, and structured error handling.
 *
 * @author Marcus Webb
 * @date 2026-04-08T05:34:15.734Z
 */

import crypto from 'crypto';

/** Webhook delivery status */
type DeliveryStatus = 'pending' | 'delivered' | 'failed' | 'retrying';

/** Webhook event envelope */
interface WebhookEvent {
  id: string;
  type: string;
  payload: Record<string, unknown>;
  createdAt: string;
}

/** Registered endpoint configuration */
interface WebhookEndpoint {
  url: string;
  secret: string;
  events: string[];
  active: boolean;
}

/** Delivery attempt record */
interface DeliveryAttempt {
  eventId: string;
  endpointUrl: string;
  status: DeliveryStatus;
  statusCode: number | null;
  attemptNumber: number;
  timestamp: string;
  error?: string;
}

/** Retry configuration */
interface RetryConfig {
  maxAttempts: number;
  baseDelayMs: number;
  maxDelayMs: number;
}

const DEFAULT_RETRY: RetryConfig = {
  maxAttempts: 3,
  baseDelayMs: 1000,
  maxDelayMs: 30_000,
};

/**
 * Compute HMAC-SHA256 signature for webhook payload verification.
 * Follows the `X-Signature-256` convention.
 */
function computeSignature(payload: string, secret: string): string {
  return `sha256=${crypto
    .createHmac('sha256', secret)
    .update(payload, 'utf8')
    .digest('hex')}`;
}

/**
 * Verify an incoming webhook signature against the expected secret.
 */
export function verifySignature(
  payload: string,
  signature: string,
  secret: string,
): boolean {
  const expected = computeSignature(payload, secret);
  if (signature.length !== expected.length) return false;
  return crypto.timingSafeEqual(
    Buffer.from(signature),
    Buffer.from(expected),
  );
}

/** Calculate exponential backoff with jitter */
function backoffDelay(attempt: number, config: RetryConfig): number {
  const exponential = config.baseDelayMs * Math.pow(2, attempt);
  const capped = Math.min(exponential, config.maxDelayMs);
  const jitter = capped * (0.5 + Math.random() * 0.5);
  return Math.round(jitter);
}

export class WebhookDispatcher {
  private endpoints: WebhookEndpoint[] = [];
  private deliveryLog: DeliveryAttempt[] = [];
  private retryConfig: RetryConfig;

  constructor(retryConfig: Partial<RetryConfig> = {}) {
    this.retryConfig = { ...DEFAULT_RETRY, ...retryConfig };
  }

  /** Register an endpoint to receive webhook events */
  registerEndpoint(endpoint: WebhookEndpoint): void {
    if (!endpoint.url || !endpoint.secret) {
      throw new Error('Endpoint must have a url and secret');
    }
    this.endpoints.push(endpoint);
  }

  /** Dispatch an event to all matching, active endpoints */
  async dispatch(event: WebhookEvent): Promise<DeliveryAttempt[]> {
    const matching = this.endpoints.filter(
      (ep) => ep.active && ep.events.includes(event.type),
    );

    const results = await Promise.allSettled(
      matching.map((ep) => this.deliverWithRetry(event, ep)),
    );

    return results.map((r) =>
      r.status === 'fulfilled'
        ? r.value
        : {
            eventId: event.id,
            endpointUrl: 'unknown',
            status: 'failed' as const,
            statusCode: null,
            attemptNumber: this.retryConfig.maxAttempts,
            timestamp: new Date().toISOString(),
            error: r.reason instanceof Error ? r.reason.message : String(r.reason),
          },
    );
  }

  /** Deliver to a single endpoint with retry */
  private async deliverWithRetry(
    event: WebhookEvent,
    endpoint: WebhookEndpoint,
  ): Promise<DeliveryAttempt> {
    const body = JSON.stringify(event);
    const signature = computeSignature(body, endpoint.secret);

    for (let attempt = 0; attempt < this.retryConfig.maxAttempts; attempt++) {
      if (attempt > 0) {
        const delay = backoffDelay(attempt, this.retryConfig);
        await new Promise((resolve) => setTimeout(resolve, delay));
      }

      const record: DeliveryAttempt = {
        eventId: event.id,
        endpointUrl: endpoint.url,
        status: 'pending',
        statusCode: null,
        attemptNumber: attempt + 1,
        timestamp: new Date().toISOString(),
      };

      try {
        const response = await fetch(endpoint.url, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'X-Webhook-Id': event.id,
            'X-Signature-256': signature,
          },
          body,
          signal: AbortSignal.timeout(10_000),
        });

        record.statusCode = response.status;

        if (response.ok) {
          record.status = 'delivered';
          this.deliveryLog.push(record);
          return record;
        }

        // 4xx errors are not retryable
        if (response.status >= 400 && response.status < 500) {
          record.status = 'failed';
          record.error = `Client error: ${response.status}`;
          this.deliveryLog.push(record);
          return record;
        }

        record.status = 'retrying';
        record.error = `Server error: ${response.status}`;
        this.deliveryLog.push(record);
      } catch (err) {
        record.status = attempt < this.retryConfig.maxAttempts - 1 ? 'retrying' : 'failed';
        record.error = err instanceof Error ? err.message : 'Unknown delivery error';
        this.deliveryLog.push(record);

        if (attempt === this.retryConfig.maxAttempts - 1) {
          return record;
        }
      }
    }

    // Should not reach here, but satisfy the compiler
    return this.deliveryLog[this.deliveryLog.length - 1];
  }

  /** Retrieve delivery log for auditing */
  getDeliveryLog(): readonly DeliveryAttempt[] {
    return this.deliveryLog;
  }
}
