// Generated by marcus-webb at 2026-04-08T15:22:00.592Z
/**
 * arc2-022 — Quick webhook retry fix
 * @author Marcus Webb
 * @date 2026-04-08T15:22:00.592Z
 *
 * Fix: webhooks were failing silently when the endpoint returned 503.
 * Added a simple retry with delay. Doesn't address the underlying
 * queue saturation issue but stops the on-call pages.
 */

import { WebhookEvent } from './types';

const RETRY_DELAY_MS = 2000;
const MAX_RETRIES = 2;

export async function sendWebhookWithRetry(
  event: WebhookEvent,
  endpointUrl: string,
): Promise<boolean> {
  for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
    try {
      const resp = await fetch(endpointUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(event),
      });

      if (resp.ok) return true;

      // Just retry on any non-ok — doesn't distinguish 4xx from 5xx
      if (attempt < MAX_RETRIES) {
        await new Promise((r) => setTimeout(r, RETRY_DELAY_MS));
      }
    } catch {
      // Swallow network errors and retry
      if (attempt < MAX_RETRIES) {
        await new Promise((r) => setTimeout(r, RETRY_DELAY_MS));
      }
    }
  }

  // Log but don't throw — the caller doesn't handle errors well
  console.error(`Webhook delivery failed after ${MAX_RETRIES + 1} attempts: ${event.id}`);
  return false;
}
