apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: acme-platform
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - api.acme.io
      secretName: acme-platform-tls
  rules:
    - host: api.acme.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: acme-platform
                port:
                  number: 80
