// Generated by sara-chen at 2026-04-08T15:22:52.213Z
/**
 * arc2-023 — Notification Email Templates
 *
 * Type-safe email template renderer with proper HTML escaping
 * and structured data binding.
 *
 * @author Sara Chen
 * @date 2026-04-08T15:22:52.213Z
 */

/** Supported notification types */
type NotificationType = 'welcome' | 'password_reset' | 'invoice' | 'alert';

/** Template data contracts per notification type */
interface TemplateDataMap {
  welcome: { userName: string; activationUrl: string };
  password_reset: { userName: string; resetUrl: string; expiresInMinutes: number };
  invoice: { userName: string; invoiceId: string; amount: string; currency: string };
  alert: { userName: string; severity: 'info' | 'warning' | 'critical'; message: string };
}

interface RenderedEmail {
  subject: string;
  html: string;
  text: string;
}

/** Escape HTML entities to prevent XSS in email bodies */
function escapeHtml(unsafe: string): string {
  return unsafe
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

/** Render a notification email with type-safe data binding */
export function renderNotification<T extends NotificationType>(
  type: T,
  data: TemplateDataMap[T],
): RenderedEmail {
  const name = escapeHtml((data as { userName: string }).userName);

  switch (type) {
    case 'welcome': {
      const d = data as TemplateDataMap['welcome'];
      const url = escapeHtml(d.activationUrl);
      return {
        subject: `Welcome to the-sprint-squeeze, ${d.userName}!`,
        html: `<h1>Welcome, ${name}!</h1><p>Activate your account: <a href="${url}">${url}</a></p>`,
        text: `Welcome, ${d.userName}! Activate your account: ${d.activationUrl}`,
      };
    }
    case 'password_reset': {
      const d = data as TemplateDataMap['password_reset'];
      const url = escapeHtml(d.resetUrl);
      return {
        subject: `Password reset for the-sprint-squeeze`,
        html: `<p>Hi ${name},</p><p>Reset your password (expires in ${d.expiresInMinutes}m): <a href="${url}">Reset</a></p>`,
        text: `Hi ${d.userName}, reset your password (expires in ${d.expiresInMinutes}m): ${d.resetUrl}`,
      };
    }
    case 'invoice': {
      const d = data as TemplateDataMap['invoice'];
      return {
        subject: `Invoice ${d.invoiceId} — the-sprint-squeeze`,
        html: `<p>Hi ${name},</p><p>Invoice <strong>${escapeHtml(d.invoiceId)}</strong>: ${escapeHtml(d.amount)} ${escapeHtml(d.currency)}</p>`,
        text: `Hi ${d.userName}, Invoice ${d.invoiceId}: ${d.amount} ${d.currency}`,
      };
    }
    case 'alert': {
      const d = data as TemplateDataMap['alert'];
      return {
        subject: `[${d.severity.toUpperCase()}] the-sprint-squeeze Alert`,
        html: `<p>Hi ${name},</p><p class="alert-${escapeHtml(d.severity)}">${escapeHtml(d.message)}</p>`,
        text: `Hi ${d.userName}, [${d.severity}] ${d.message}`,
      };
    }
    default:
      throw new Error(`Unknown notification type: ${String(type)}`);
  }
}
