// Generated by sara-chen at 2026-04-08T15:22:52.213Z
/**
 * arc2-023 — Barrel Export
 *
 * Re-exports public API for the invoice-notification-template module.
 *
 * @author Sara Chen
 * @date 2026-04-08T15:22:52.213Z
 */

// --- Types ---
export type { Config } from './config.js';
export type { Record, CreateInput } from './types.js';

// --- Core ---
export { default as Router } from './routes.js';
export { Service } from './service.js';

// --- Utilities ---
export { validate } from './validation.js';
