// Generated by sara-chen at 2026-04-08T05:40:17.297Z
/**
 * arc1-004 — Barrel Export
 *
 * Re-exports public API for the email-and-slack-notification-channels module.
 *
 * @author Sara Chen
 * @date 2026-04-08T05:40:17.297Z
 */

// --- Types ---
export type { Config } from './config.js';
export type { Record, CreateInput } from './types.js';

// --- Core ---
export { default as Router } from './routes.js';
export { Service } from './service.js';

// --- Utilities ---
export { validate } from './validation.js';
