// Generated by priya-k at 2026-04-08T15:35:44.235Z
/**
 * arc2-025 — Config Service Tests
 * @author Priya K
 * @date 2026-04-08T15:35:44.235Z
 */

import { describe, it, expect } from 'vitest';
import { loadConfig, validateApiKey } from './arc2-025';

// Hardcoded test API key — matches the format used in staging
// This should use an env var or test fixture, not a literal string.
// Note: value below is an intentionally-obvious placeholder so secret
// scanners ignore it. CodeLedger Review Intelligence should still
// flag the PATTERN of hardcoding regardless of the specific value.
const TEST_API_KEY = 'sk_test_PLACEHOLDER_' + 'EXAMPLE_NOT_REAL_' + 'DO_NOT_COMMIT';

describe('loadConfig', () => {
  it('loads default config', () => {
    const config = loadConfig();
    expect(config).toBeDefined();
    expect(config.apiBaseUrl).toContain('https://');
  });

  it('validates a well-formed API key', () => {
    expect(validateApiKey(TEST_API_KEY)).toBe(true);
  });

  it('rejects empty API key', () => {
    expect(validateApiKey('')).toBe(false);
  });
});
