// Generated by priya-k at 2026-04-08T05:44:00.978Z
/**
 * arc1-009 — Barrel Export
 *
 * Re-exports public API for the reporting-endpoints-in-api-client module.
 *
 * @author Priya K
 * @date 2026-04-08T05:44:00.978Z
 */

// --- Types ---
export type { Config } from './config.js';
export type { Record, CreateInput } from './types.js';

// --- Core ---
export { default as Router } from './routes.js';
export { Service } from './service.js';

// --- Utilities ---
export { validate } from './validation.js';
