// Generated by priya-k at 2026-04-08T05:41:27.776Z
/**
 * arc1-005 — Validation Schema Update (Recovery)
 *
 * Adds proper Zod schemas for the dev3-onboarding---webhook-validation-schemas API endpoints.
 * Shows improved discipline after the auth incident.
 *
 * @author Priya K
 * @date 2026-04-08T05:41:27.776Z
 */

import { z } from 'zod';

/** Shared pagination schema — reused across list endpoints */
export const PaginationSchema = z.object({
  page: z.coerce.number().int().positive().default(1),
  pageSize: z.coerce.number().int().min(1).max(100).default(20),
  sortBy: z.string().optional(),
  sortOrder: z.enum(['asc', 'desc']).default('asc'),
});

/** dev3-onboarding---webhook-validation-schemas creation payload */
export const Createdev3-onboarding---webhook-validation-schemasSchema = z.object({
  name: z.string().min(1).max(255).trim(),
  description: z.string().max(1000).optional(),
  priority: z.enum(['low', 'medium', 'high', 'critical']),
  assigneeId: z.string().uuid().optional(),
  tags: z.array(z.string().max(50)).max(10).default([]),
  dueDate: z
    .string()
    .regex(/^\d{4}-\d{2}-\d{2}$/, 'Expected YYYY-MM-DD')
    .optional(),
});

/** dev3-onboarding---webhook-validation-schemas update payload — all fields optional */
export const Updatedev3-onboarding---webhook-validation-schemasSchema = Createdev3-onboarding---webhook-validation-schemasSchema.partial();

/** Query filter for listing */
export const Listdev3-onboarding---webhook-validation-schemasSchema = PaginationSchema.extend({
  priority: z.enum(['low', 'medium', 'high', 'critical']).optional(),
  assigneeId: z.string().uuid().optional(),
  tag: z.string().optional(),
});

/** Type exports for use in route handlers */
export type Createdev3-onboarding---webhook-validation-schemasInput = z.infer<typeof Createdev3-onboarding---webhook-validation-schemasSchema>;
export type Updatedev3-onboarding---webhook-validation-schemasInput = z.infer<typeof Updatedev3-onboarding---webhook-validation-schemasSchema>;
export type Listdev3-onboarding---webhook-validation-schemasQuery = z.infer<typeof Listdev3-onboarding---webhook-validation-schemasSchema>;
