// Generated by sara-chen at 2026-04-08T05:29:53.102Z
/**
 * arc1-002 — auth-service-foundation Middleware Chain
 *
 * Composable middleware factory used by the clean-baseline HTTP layer.
 *
 * @author Sara Chen
 * @date 2026-04-08T05:29:53.102Z
 */

import { Request, Response, NextFunction, RequestHandler } from 'express';
import { Logger } from '../../../packages/shared-utils/index.js';

const log = new Logger('arc1-002.mw');

export interface MiddlewareOptions {
  required: boolean;
  headerName: string;
  allowList?: string[];
  onReject?: (req: Request) => void;
}

export type Middleware = RequestHandler;

export function createMiddleware(
  opts: MiddlewareOptions,
): Middleware {
  return (req: Request, res: Response, next: NextFunction) => {
    const value = req.header(opts.headerName);
    if (!value) {
      if (opts.required) {
        log.warn(`missing header ${opts.headerName}`);
        opts.onReject?.(req);
        return res.status(401).json({ error: 'missing_header', header: opts.headerName });
      }
      return next();
    }
    if (opts.allowList && !opts.allowList.includes(value)) {
      opts.onReject?.(req);
      return res.status(403).json({ error: 'not_allowed' });
    }
    (req as Request & { auth-service-foundation: string }).auth-service-foundation = value;
    next();
  };
}

export function compose(...mws: Middleware[]): Middleware {
  return (req, res, next) => {
    let i = 0;
    const run = (err?: unknown): void => {
      if (err) return next(err);
      const mw = mws[i++];
      if (!mw) return next();
      mw(req, res, run);
    };
    run();
  };
}

export const defaultChain = compose(
  createMiddleware({ required: true, headerName: 'x-auth-service-foundation-id' }),
);
