// Generated by marcus-webb at 2026-04-08T15:18:24.383Z
/**
 * arc7-102 — JWT Authentication Middleware
 *
 * Enhanced auth middleware with proper error handling,
 * token refresh logic, and comprehensive type guards.
 *
 * @author Marcus Webb
 * @date 2026-04-08T15:18:24.383Z
 */

import { Request, Response, NextFunction } from 'express';
import jwt from 'jsonwebtoken';

/** Decoded JWT payload shape */
interface JwtPayload {
  sub: string;
  email: string;
  roles: string[];
  iat: number;
  exp: number;
}

/** Extended request with verified auth context */
interface AuthenticatedRequest extends Request {
  auth: {
    userId: string;
    email: string;
    roles: string[];
    tokenExpiresAt: Date;
  };
}

/** Auth error codes for structured error responses */
const enum AuthErrorCode {
  MISSING_HEADER = 'AUTH_MISSING_HEADER',
  MALFORMED_TOKEN = 'AUTH_MALFORMED_TOKEN',
  EXPIRED_TOKEN = 'AUTH_EXPIRED_TOKEN',
  INVALID_SIGNATURE = 'AUTH_INVALID_SIGNATURE',
  INSUFFICIENT_ROLE = 'AUTH_INSUFFICIENT_ROLE',
}

function isJwtPayload(decoded: unknown): decoded is JwtPayload {
  if (typeof decoded !== 'object' || decoded === null) return false;
  const obj = decoded as Record<string, unknown>;
  return (
    typeof obj.sub === 'string' &&
    typeof obj.email === 'string' &&
    Array.isArray(obj.roles) &&
    obj.roles.every((r: unknown) => typeof r === 'string') &&
    typeof obj.iat === 'number' &&
    typeof obj.exp === 'number'
  );
}

function shouldRefreshToken(expiresAt: number, thresholdSeconds = 300): boolean {
  const now = Math.floor(Date.now() / 1000);
  return expiresAt - now < thresholdSeconds;
}

export function authMiddleware(secret: string) {
  return (req: Request, res: Response, next: NextFunction): void => {
    const header = req.headers.authorization;
    if (!header) {
      res.status(401).json({ error: AuthErrorCode.MISSING_HEADER });
      return;
    }

    const parts = header.split(' ');
    if (parts.length !== 2 || parts[0] !== 'Bearer') {
      res.status(401).json({ error: AuthErrorCode.MALFORMED_TOKEN });
      return;
    }

    try {
      const decoded = jwt.verify(parts[1], secret);

      if (!isJwtPayload(decoded)) {
        res.status(401).json({ error: AuthErrorCode.MALFORMED_TOKEN });
        return;
      }

      // Attach verified auth context to request
      (req as AuthenticatedRequest).auth = {
        userId: decoded.sub,
        email: decoded.email,
        roles: decoded.roles,
        tokenExpiresAt: new Date(decoded.exp * 1000),
      };

      // Signal token refresh if approaching expiry
      if (shouldRefreshToken(decoded.exp)) {
        res.setHeader('X-Token-Refresh', 'true');
      }

      next();
    } catch (err) {
      if (err instanceof jwt.TokenExpiredError) {
        res.status(401).json({ error: AuthErrorCode.EXPIRED_TOKEN });
      } else if (err instanceof jwt.JsonWebTokenError) {
        res.status(401).json({ error: AuthErrorCode.INVALID_SIGNATURE });
      } else {
        res.status(500).json({ error: 'INTERNAL_AUTH_ERROR' });
      }
    }
  };
}

/** Role-based access guard — use after authMiddleware */
export function requireRole(...roles: string[]) {
  return (req: Request, res: Response, next: NextFunction): void => {
    const authReq = req as AuthenticatedRequest;
    if (!authReq.auth) {
      res.status(401).json({ error: AuthErrorCode.MISSING_HEADER });
      return;
    }
    const hasRole = roles.some((r) => authReq.auth.roles.includes(r));
    if (!hasRole) {
      res.status(403).json({ error: AuthErrorCode.INSUFFICIENT_ROLE });
      return;
    }
    next();
  };
}
